# This project config file describes your project. See looper docs for details.

metadata:
  sample_annotation: test_annotation.csv  # sheet listing all samples in the project
  output_dir: test_out  # ABSOLUTE PATH to the parent, shared space where project results go
  pipelines_dir: "../"  # ABSOLUTE PATH the directory where looper will find the pipeline repository
  merge_table: null  # (optional) input for samples with more than one input file

# in your sample_annotation, columns with these names will be populated as described 
# in the data_sources section below
derived_columns: [read1, read2]  

data_sources:  # This section describes paths to your data
  # specify the ABSOLUTE PATH of input files using variable path expressions
  # These keys then correspond to values in your sample annotation columns.
  # Variables specified using brackets are populated from sample_annotation columns. 
  # Variable syntax: {column_name}. For example, use {sample_name} to populate
  # the file name with the value in the sample_name column for each sample.
  # example_data_source: "/path/to/data/{sample_name}_R1.fastq.gz"
  test_data_R1: "test_data/{sample_name}_R1.fastq.gz"
  test_data_R2: "test_data/{sample_name}_R2.fastq.gz"

genomes:
  human: hg19
  mouse: mm9
