ATACseq.py:
  name: ATACseq
  looper_args: True
  required_input_files: [read1, read2]
  all_input_files: [read1, read2]
  ngs_input_files: [read1, read2]
  arguments:
    "--sample-name": sample_name
    "--genome": genome
    "--input": read1
    "--input2": read2
    "--single-or-paired": read_type
  optional_arguments:
    "--frip-ref-peaks": FRIP_ref
    "--prealignments": prealignments
    "--genome-size": macs_genome_size
  resources:
    default:
      file_size: "0"
      cores: "2"
      mem: "4000"
      time: "0-04:00:00"
    normal:
      file_size: "0.5"
      cores: "4"
      mem: "16000"
      time: "2-00:00:00"
    large:
      file_size: "6"
      cores: "8"
      mem: "32000"
      time: "3-00:00:00"
