# This project config file describes your project. See looper docs for details.
pep_version: 2.1.0
# relative paths are relative to this config file
sample_table: "gold_atac_annotation.csv"  # sheet listing all samples in the project (relative to this file)

looper:  
  output_dir: "$PROCESSED/pepatac/gold_atac" # ABSOLUTE PATH to the parent, shared space where project results go
  pipeline_interfaces: ["$CODE/pepatac/project_pipeline_interface.yaml"]

sample_modifiers:
  append:
    pipeline_interfaces: ["$CODE/pepatac/sample_pipeline_interface.yaml"]
  derive:
    # in your sample_table, columns with these names will be populated as 
    # described in the sources section
    attributes: [read1, read2]
    sources:
      # specify the ABSOLUTE PATH of input files using variable path expressions
      # These keys then correspond to values in your sample annotation columns.
      # Variables specified using brackets are populated from sample_annotation columns. 
      # Variable syntax: {column_name}. For example, use {sample_name} to populate
      # the file name with the value in the sample_name column for each sample.
      # example_data_source: "/path/to/data/{sample_name}_R1.fastq.gz"
      SRA: "$SRABAM/{SRR}.bam"
      SRA_1: "$SRAFQ/{SRR}_1.fastq.gz"
      SRA_2: "$SRAFQ/{SRR}_2.fastq.gz"
  imply:
    - if: 
        organism: ["human", "Homo sapiens", "Human", "Homo_sapiens"]
      then: 
        genome: hg38
        macs_genome_size: hs
        prealignments: rCRSd human_repeats
        deduplicator: samblaster # Default. [options: picard]
        trimmer: skewer          # Default. [options: pyadapt, trimmomatic]
        peak_type: fixed         # Default. [options: variable]
        extend: "250"            # Default. For fixed-width peaks, extend this distance up- and down-stream.
        frip_ref_peaks: None     # Default. Use an external reference set of peaks instead of the peaks called from this run
        blacklist: $GENOMES/hg38/blacklist/default/hg38_blacklist.bed.gz
